import { useEffect, useState } from "react";
import { TOKEN, collectionUrl } from "./chain.ts";
import { Address } from "./Address.tsx";
import { BRAND_NAME, BRAND_FULL } from "./brand.ts";
import { Mark } from "../components/ui";

/**
 * The $PWA page.
 *
 * Pons runs on Robinhood Chain, the same chain as our contracts, so once the token launches
 * both the accrued fees and the market cap are readable straight from chain over the RPC we
 * already use. There is no Pons API to depend on (api.ponsfamily.com does not resolve and
 * the app ships no public endpoints), and none is needed.
 *
 * Until launch, TOKEN.address is undefined and this page says so plainly rather than showing
 * zeroes. A zero next to "Fees earned" reads as "this is live and nobody is trading",
 * which would be a lie about a token that does not exist yet.
 */

/**
 * What /api/token/stats returns. `live` is the server's answer, not ours.
 *
 * The page used to decide "is the token launched?" from VITE_TOKEN_ADDRESS while the numbers
 * came from the API, so launching meant setting the address in TWO places and a stale bundle
 * could disagree with the worker. Every other two-place config in this codebase has produced
 * a bug. The API now decides, and it reads the address from the same env the Pons reader uses.
 */
type Stats = {
  live: boolean;
  tokenAddress?: string;
  feesEth?: number;
  feesUsd?: number;
  marketCapUsd?: number;
} | null;

const usd = (n: number) =>
  `$${n.toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="tok-stat">
      <span className="tok-stat-label">{label}</span>
      <span className="tok-stat-value">{value}</span>
    </div>
  );
}

export function TokenPage() {
  const [stats, setStats] = useState<Stats>(null);
  // The server decides. TOKEN.address is only a fallback for showing the CA immediately.
  const live = stats?.live === true;
  const contract = stats?.tokenAddress ?? TOKEN.address;

  useEffect(() => {
    // Post-launch: poll the Pons fee contract and the pool for price. Both are on chain 4663
    // and readable with the public client already configured, so this becomes a contract
    // read rather than a new integration.
    let cancelled = false;
    const poll = async () => {
      try {
        const res = await fetch(`/api/token/stats`, { signal: AbortSignal.timeout(10_000) });
        if (!res.ok) return;
        const body = (await res.json()) as Stats;
        if (!cancelled) setStats(body);
      } catch {
        /* a stats hiccup must not blank the page */
      }
    };
    void poll();
    const t = setInterval(poll, 15_000);
    return () => {
      cancelled = true;
      clearInterval(t);
    };
  }, []);

  return (
    <div className="tok">
      {/*
        Split, left-aligned, and not a centred column.
        
        Every previous version of this page was a centred stack — mark, title, lead, pill,
        then sections down the middle — and no amount of restyling the pieces changed the
        fact that the SHAPE was the thing being recognised. The narrative now runs down the
        left and the numbers sit in a panel on the right, which is a different page rather
        than the same page in different clothes.
      */}
      <section className="tok-top">
        <div className="tok-intro">
          {/* The mark alone. A pill sized for a word looks like a broken label with the
              word removed, so this is a plain circular mark instead. */}
          <span className="tok-badge" aria-hidden="true">
            <Mark size={40} />
          </span>
          <h1>{BRAND_FULL}</h1>
          <p className="tok-lead">
            The fees generated by our token are distributed to active {BRAND_NAME} users
            through ongoing rewards while also covering platform costs.
          </p>
          {contract ? (
            <div className="tok-ca">
              <Address label="CA" value={contract} href={collectionUrl(contract, true)} />
            </div>
          ) : (
            <div className="tok-ca tok-ca-pending">
              <span className="addr-label">CA</span>
              <code>Not launched yet</code>
            </div>
          )}
        </div>

        <aside className="tok-board" aria-label="Token figures">
          <Stat
            label="Fees earned"
            value={live && stats?.feesUsd != null ? usd(stats.feesUsd) : "—"}
          />
          <Stat
            label="Market cap"
            value={live && stats?.marketCapUsd != null ? usd(stats.marketCapUsd) : "—"}
          />
        </aside>
      </section>

      {/*
        Two reward categories, not a numbered sequence.

        These were steps 1-3 of a process, so they carried numbers. They are now two
        answers to "who", which have no order — numbering them would imply Holders comes
        before Leaderboards, which means nothing.
      */}
      <section className="tok-band tok-band-centered">
        <h2 className="tok-h2">Who gets rewarded</h2>
        <div className="tok-who">
          <div className="tok-who-item">
            <h3>Holders</h3>
            <p>
              Wallets holding between 0.25% and 4% of the token supply are eligible to
              receive free packs as rewards over time.
            </p>
          </div>
          <div className="tok-who-item">
            <h3>Leaderboards</h3>
            <p>
              The top participants on the leaderboard earn free packs over time, rewarding
              those who contribute to the {BRAND_NAME} ecosystem.
            </p>
          </div>
        </div>
        <p className="tok-note">Rewards are distributed as free packs</p>
      </section>

      {/*
        Same FAQ pattern as the How it works page, reusing its markup and classes so the two
        read as one system. The band is not centered like "Who gets rewarded": FAQ answers are
        prose and belong left-aligned, so tok-faq constrains the width and centers the block
        while the text stays left.
      */}
      <section className="tok-band" id="token-questions">
        <h2 className="tok-h2 tok-faq-h2">Questions</h2>
        <div className="tok-faq">
          <div className="hiw-faq">
            {[
              {
                q: "Do I need to hold the token to open packs?",
                a: `No. Packs are opened with USDG at Collector Crypt's price whether or not you hold the token. Holding it only makes you eligible for the holder rewards, and taking part in the platform is what places you on the leaderboard.`,
              },
              {
                q: "How do users get rewarded?",
                a: `Every 12 hours the eligible holders are entered into a raffle, and one of them receives a free pack. Separately, the top spots on the leaderboard earn exclusive rewards each week for contributing to the ${BRAND_NAME} ecosystem, and the leaderboard resets once the week is over.`,
              },
              {
                q: "How do I claim a reward pack?",
                a: `There is nothing to claim. Reward packs are distributed to eligible wallets automatically.`,
              },
              {
                q: "What are the platform costs?",
                a: "Running the platform has real costs. Every pack is bought on Collector Crypt and bridged across chains, which carries bridging fees, gas, and the running cost of the service that fulfils each order. The fees generated by our token cover these costs, so you pay the same price you would pay on Collector Crypt. We are in contact with Collector Crypt to bring these costs down further over time.",
              },
              {
                q: "Will the token fees be used for other things in the future?",
                a: "Over time we plan to add a wider variety of rewards and run events for the community. For now we are keeping it simple while we test everything and make sure it works reliably, and we are still building out our relationship with Collector Crypt.",
              },
              {
                q: "Why on Robinhood?",
                a: "Robinhood Chain was built for real world assets, and graded Pokemon cards have been some of the best performing real world assets on chain. They deserve a place on Robinhood. The chain is still growing, and we want to help bring a new kind of audience into real world assets on Robinhood.",
              },
            ].map((f) => (
              <details className="hiw-faq-item" key={f.q}>
                <summary>
                  <span>{f.q}</span>
                  <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
                    <path d="M6 9.5l6 6 6-6" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </summary>
                <p>{f.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

    </div>
  );
}
